// Builds apps/mockup/index.html: ONE self-contained file that opens by double-click, assembled from
// the design system package (tokens, components, icons, font, logo) and the app sources in ./src.
// Because the mockup is built from the package rather than a hand-copied snapshot, the two can no
// longer drift apart. Run: node apps/mockup/build.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ds = join(here, '..', '..', 'packages', 'design-system');
const b64 = p => readFileSync(p).toString('base64');

const font = 'data:font/woff2;base64,' + b64(join(ds, 'fonts', 'Inter-latin-wght.woff2'));
const tokens = readFileSync(join(ds, 'tokens.css'), 'utf8')
  .replace(/src:\s*url\("\.\/fonts\/Inter-latin-wght\.woff2"\)[^;]*;/, `src: url("${font}") format("woff2");`);
const components = readFileSync(join(ds, 'components.css'), 'utf8').replace(/@import\s+"\.\/tokens\.css";/, '');
const icons = readFileSync(join(ds, 'icons.svg'), 'utf8');
const logo = 'data:image/png;base64,' + b64(join(ds, 'assets', 'top1movers-logo.png'));
const srcDir = join(here, 'src');
const js = readdirSync(srcDir).filter(f => f.endsWith('.js')).sort()
  .map(f => `/* ---- src/${f} ---- */\n` + readFileSync(join(srcDir, f), 'utf8')).join('\n');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#1c2050">
<title>Top1Movers Operations Portal</title>
<!-- GENERATED by apps/mockup/build.mjs. Do not edit this file: edit packages/design-system/* or apps/mockup/src/* and rebuild. -->
<style>
${tokens}
${components}
</style>
</head>
<body>
${icons}
<div id="app"></div>
<div id="drawerRoot" class="ds-overlay"></div>
<div id="cmdkRoot" class="ds-cmdk-root" onclick="if(event.target===this) closeCmdk()"></div>
<div id="acctPickerRoot" class="ds-acct-root" onclick="if(event.target===this) closeAcctPicker()"></div>
<div id="toastRoot" class="ds-toasts" aria-live="polite"></div>
<script>
const LOGO_SRC = "${logo}";
${js}
</script>
</body>
</html>
`;
writeFileSync(join(here, 'index.html'), html);
console.log('Built apps/mockup/index.html', (html.length / 1024).toFixed(0) + ' KB');
